name: bet_smart_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.11

flutter:
  assets:
      - assets/images/on_boarding_background/
      - assets/images/on_boarding_app_screens/
      - assets/images/tabs_logo/
      - assets/images/
      - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_Medium.ttf
          weight: 500
  uses-material-design: true
